### ISSUE TITLE
pep517 is now pyproject-hooks

### ISSUE THREAD

**Issue by theAeon** [conda-forge/pep517-feedstock#18]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://discuss.python.org/t/pep517-is-now-pyproject-hooks/21275

Project was renamed. Not sure how conda-forge handles this kind of thing.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by ocefpaf** [comment]
> Project was renamed. Not sure how conda-forge handles this kind of thing.

If you need `pyproject-hooks` we need to submit it as a new package with that name to staged-recipes. This one will be archived.
